# Generated by Django 2.2.6 on 2020-03-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20200321_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeks',
            options={'verbose_name': 'Неделя', 'verbose_name_plural': 'Недели'},
        ),
        migrations.AddField(
            model_name='classroom',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество мест в аудитории'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='students_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество студентов'),
        ),
        migrations.AddField(
            model_name='subject',
            name='load',
            field=models.IntegerField(blank=True, null=True, verbose_name='Нагрузка (часов в семестр)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Название предмета', max_length=100, unique=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(blank=True, choices=[('Lecture', 'Лекция'), ('Practice', 'Практика'), ('Lab', 'Лабораторная работа')], default=None, max_length=40, null=True, verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Текущая'),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='week',
            field=models.CharField(max_length=10, verbose_name='Неделя'),
        ),
    ]
