# Generated by Django 2.2.6 on 2020-03-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20200323_1933'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonfulltime',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lessonfulltime',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='lessonfulltime',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='lessonfulltime',
            name='study_group',
        ),
        migrations.RemoveField(
            model_name='lessonfulltime',
            name='subject',
        ),
        migrations.DeleteModel(
            name='LessonDistance',
        ),
        migrations.DeleteModel(
            name='LessonFulltime',
        ),
    ]
