# Generated by Django 2.2.6 on 2020-03-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_lessondistance_lessonfulltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondistance',
            name='study_group',
            field=models.ForeignKey(limit_choices_to={'mode_of_study': 'distance'}, on_delete=django.db.models.deletion.CASCADE, to='schedule.StudyGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='lessonfulltime',
            name='day',
            field=models.CharField(blank=True, choices=[('Mon', 'пн'), ('Tue', 'вт'), ('Wed', 'ср'), ('Thu', 'чт'), ('Fri', 'пт'), ('Sat', 'сб')], max_length=10, null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='lessonfulltime',
            name='study_group',
            field=models.ForeignKey(limit_choices_to={'mode_of_study': 'fulltime'}, on_delete=django.db.models.deletion.CASCADE, to='schedule.StudyGroup', verbose_name='Группа'),
        ),
    ]
