# Generated by Django 2.2.6 on 2020-03-25 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20200325_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Speaker', verbose_name='Преподаватель'),
        ),
    ]
