# Generated by Django 2.2.6 on 2020-03-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_subject_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='speaker',
        ),
        migrations.AddField(
            model_name='subject',
            name='speaker',
            field=models.ManyToManyField(blank=True, to='schedule.Speaker', verbose_name='Преподаватель'),
        ),
    ]
