# Generated by Django 2.2.6 on 2020-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_auto_20200326_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='speaker',
        ),
        migrations.AddField(
            model_name='subject',
            name='classrooms',
            field=models.ManyToManyField(blank=True, to='schedule.Classroom', verbose_name='Аудитории, в которых может проводиться занятие'),
        ),
        migrations.AddField(
            model_name='subject',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='schedule.Speaker', verbose_name='Преподаватели, которые могут вести предмет'),
        ),
    ]
