# Generated by Django 2.2.6 on 2020-03-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_auto_20200326_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='classrooms',
            field=models.ManyToManyField(blank=True, help_text='<span style="color: black; font-weight: 500;">Аудитории, в которых проводится занятие<pre>\n</pre></span>', to='schedule.Classroom', verbose_name='Аудитории'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='speakers',
            field=models.ManyToManyField(blank=True, help_text='<span style="color: black; font-weight: 500;">Преподаватели, ведут предмет<pre>\n</pre></span>', to='schedule.Speaker', verbose_name='Преподаватели'),
        ),
        migrations.CreateModel(
            name='SpeakerBlockedTimeFulltime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Номер пары')),
                ('week_parity', models.CharField(blank=True, choices=[('even', 'Четная'), ('uneven', 'Нечетная')], max_length=10, null=True, verbose_name='Неделя')),
                ('day', models.CharField(blank=True, choices=[('Mon', 'пн'), ('Tue', 'вт'), ('Wed', 'ср'), ('Thu', 'чт'), ('Fri', 'пт'), ('Sat', 'сб')], max_length=10, null=True, verbose_name='День')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Speaker', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Заблокированное время у преподавателя (дневное расписание)',
                'verbose_name_plural': 'Заблокированное время у преподавателя (дневное расписание)',
            },
        ),
        migrations.CreateModel(
            name='SpeakerBlockedTimeDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_day', models.DateField(blank=True, null=True, verbose_name='Дата занятия')),
                ('class_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Номер пары')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Speaker', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Заблокированное время у преподавателя (заочное расписание)',
                'verbose_name_plural': 'Заблокированное время у преподавателя (заочное расписание)',
            },
        ),
    ]
