# Generated by Django 2.2.6 on 2020-03-28 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_auto_20200328_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=5, verbose_name='Номер')),
                ('weeks_count_fulltime', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=5, verbose_name='Кол-во недель (дневное)')),
                ('weeks_count_distance', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=5, verbose_name='Кол-во недель (вечернее)')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестры',
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='load',
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_count', models.CharField(max_length=5, verbose_name='Кол-во часов')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.StudyGroup', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Нагрузка',
                'verbose_name_plural': 'Нагрузка',
            },
        ),
    ]
