# Generated by Django 2.2.6 on 2020-03-28 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_auto_20200328_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Term', verbose_name='Семестр'),
        ),
    ]
