# Generated by Django 2.2.6 on 2020-04-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_lessonfulltime_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='distance_first_day',
            field=models.DateField(null=True, verbose_name='Первый день сессии заочников'),
        ),
        migrations.AddField(
            model_name='term',
            name='distance_last_day',
            field=models.DateField(null=True, verbose_name='Последний день сессии заочников'),
        ),
    ]
